#!/bin/bash

echo "==================================="
echo "HARDWARE VERBINDUNGS-CHECK"
echo "==================================="
echo ""
echo "Bitte überprüfe folgende Verbindungen:"
echo ""
echo "ENV III Modul (Indoor Sensor):"
echo "-------------------------------"
echo "ENV III Pin → Raspberry Pi Pin"
echo "VCC (rot)   → Pin 1 (3.3V)"
echo "GND (schwarz) → Pin 9 (Ground)"
echo "SDA (gelb)  → Pin 3 (GPIO2/SDA)"
echo "SCL (weiß)  → Pin 5 (GPIO3/SCL)"
echo ""
echo "DHT22 Sensor (Outdoor):"
echo "-----------------------"
echo "DHT22 Pin → Raspberry Pi Pin"
echo "Pin 1 (VCC) → Pin 1 (3.3V)"
echo "Pin 2 (Data) → Pin 7 (GPIO4)"
echo "Pin 3 (NC) → nicht verbunden"
echo "Pin 4 (GND) → Pin 9 (Ground)"
echo ""
echo "WICHTIGE SCHRITTE:"
echo "=================="
echo ""
echo "1. Raspberry Pi herunterfahren:"
echo "   sudo shutdown -h now"
echo ""
echo "2. Stromversorgung trennen"
echo ""
echo "3. Alle Kabelverbindungen prüfen:"
echo "   - Sitzt jedes Kabel fest?"
echo "   - Sind die Pins richtig?"
echo "   - Keine gebrochenen Kabel?"
echo ""
echo "4. Raspberry Pi wieder starten"
echo ""
echo "5. Nach dem Neustart ausführen:"
echo "   ./fix_i2c_baudrate.sh"
echo "   sudo reboot"
echo ""
echo "6. Nach zweitem Neustart testen:"
echo "   python3 sensor_diagnostics.py"
echo ""
echo "Falls immer noch keine Sensoren erkannt werden:"
echo "- Andere Jumperkabel verwenden"
echo "- Direkt an GPIO-Pins löten"
echo "- Sensor-Module auf Beschädigung prüfen"